name: aws-iot-sample-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"

      # - name: Publish
      #   run: dotnet publish --configuration Release --output ./out

      - name: Deploy to AWS Lambda
        run: dotnet lambda deploy-function --region $AWS_REGION
