name: aws-iot-sample-sam-deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARTIFACTS_BUCKET: ${{ secrets.ARTIFACTS_BUCKET }}
  SAM_TEMPLATE: template.yaml
  STACK_NAME: aws-iot-sample-stack
  # PROD_PIPELINE_EXECUTION_ROLE:
  # PROD_CLOUDFORMATION_EXECUTION_ROLE:

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - run: |
          dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"

  build-package:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Build resources
        run: sam build --template ${SAM_TEMPLATE}

      - name: Upload artifacts to bucket
        run: |
          sam package \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --region ${AWS_REGION} \
            --output-template-file packaged.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: packaged.yaml
          path: packaged.yaml

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: aws-lambda-test

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - uses: actions/download-artifact@v3
        with:
          name: packaged.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Deploy resources to cloud
        run: |
          sam deploy --stack-name ${STACK_NAME} \
            --template packaged.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${AWS_REGION} \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --no-fail-on-empty-changeset

  integration-test:
    if: github.ref == 'refs/heads/main'
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # trigger the integration tests here
