name: aws-iot-sample-destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy AWS Lambda"
        required: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: aws-lambda-test

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Destroy AWS Lambda
        working-directory: ./src/aws-iot-sample
        run: dotnet lambda delete-function MyFunction

      - name: Destroy HandheldAlertHandler
        working-directory: ./src/HandheldAlertHandler
        run: dotnet lambda delete-function HandheldAlertHandler

      - name: Destroy VehicleLocationWriter
        working-directory: ./src/VehicleLocationWriter
        run: dotnet lambda delete-function VehicleLocationWriter
