name: aws-iot-sample-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy AWS Lambda"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: aws-lambda-test
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Deploy to AWS Lambda
        working-directory: ./src/aws-iot-sample
        run: dotnet lambda deploy-function --function-name MyFunction --function-role MyFunction.role --disable-interactive true

  destroy:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Destroy AWS Lambda
        working-directory: ./src/aws-iot-sample
        run: dotnet lambda delete-function MyFunction
